trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: false
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder:
  - "discord.js"
  - "<THIRD_PARTY_MODULES>"
  - "^[./]"
  - "^@/(.*)$"
importOrderSeparation: true
importOrderSortSpecifiers: true
