services:
  db:
    image: postgres:latest
    container_name: finalist-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: finalist-redis
    ports:
      - "6379:6379"
